#!/bin/bash

IMG="akshaal/akki-test-env"
KEEP_VERSIONS=3

D=$(dirname "$0")
cd "$D"

info() {
    echo "$akc_prompt####$akc_default $1$akc_default"
}

AKKI_VERSION=$(git describe --tags --always)

if test "x$AKKI_VERSION" = "x"; then
    echo "Unable to determine version!"
    exit 16
fi

export LANG=C

. ./docker-ext-image-versions.env

info "Building image ${akc_good}$AKKI_TAG$akc_default"

docker build -t "$IMG:$AKKI_VERSION" \
            --build-arg ALPINE_VERSION="$ALPINE_VERSION" \
            --build-arg SIMULAVR_TAG="$SIMULAVR_TAG" \
            --build-arg KLIPPER_TAG="$KLIPPER_TAG" \
            --build-arg OCTOPRINT_TAG="$OCTOPRINT_TAG" \
            . || exit 202

clean() {
    ids=$(docker image inspect -f "{{ .Created }} {{ .Id }}" $(docker image ls $IMG -q --no-trunc) | sort -r | cut -f2 -d" " | tail -n +`expr $KEEP_VERSIONS + 1`)

    IFS=$'\n'
    for id in $ids; do
        info "${akc_good}Removing an old image: ${akc_value}$(docker image inspect -f '{{.RepoTags}}' $id)${akc_default}"
        docker image rm "$id"
    done
}

echo
info "Current images:"
docker image ls "$IMG"
